set(CMAKE_BUILD_TYPE RELEASE CACHE STRING "")
set(CMAKE_INSTALL_PREFIX "/home/mark/Programming/8/4th_grade/Compiler/llvm-project/install" CACHE STRING "")
set(LLVM_ENABLE_PROJECTS
  clang CACHE STRING "")
set(CLANG_BUILD_EXAMPLES OFF CACHE BOOL "")
set(LLVM_BUILD_TESTS OFF CACHE BOOL "")
set(LLVM_ENABLE_ASSERTIONS ON CACHE BOOL "")
set(LLVM_OPTIMIZED_TABLEGEN ON CACHE BOOL "")
set(LLVM_PARALLEL_COMPILE_JOBS 5 CACHE STRING "")
set(LLVM_PARALLEL_LINK_JOBS 1 CACHE STRING "")
set(LLVM_TARGETS_TO_BUILD
  X86 CACHE STRING "")
set(CLANG_ENABLE_STATIC_ANALYZER OFF CACHE BOOL "")
set(CLANG_ENABLE_ARCMT OFF CACHE BOOL "")
